app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__, template_folder='templates')

from . import routes  # Import routes at the end to avoid circular imports

app/student/routes.py
from flask import render_template
from . import student
from app.utils.decorators import login_required, roles_required

@student.route("/dashboard")
@login_required
@roles_required("student")
def dashboard():
    return render_template("student/dashboard.html")

@student.route('/attendance')
@login_required
@roles_required("student")
def attendance():
    return render_template("student/attendance.html")

@student.route("/change_ip")
@login_required
@roles_required("student")
def change_ip():
    return render_template("student/change_ip.html")

@student.route("/change_password")
@login_required
@roles_required("student")
def change_password():
    return render_template("student/change_password.html")

@student.route("/leave")
@login_required
@roles_required("student")
def leave():
    return render_template("student/leave.html")

@student.route("/profile")
@login_required
@roles_required("student")
def profile():
    return render_template("student/profile.html")

@student.route("/scan_qr")
@login_required
@roles_required("student")
def scan_qr():
    return render_template("student/scan_qr.html")

@student.route("/timetable")
@login_required
@roles_required("student")
def timetable():
    return render_template("student/timetable.html")

@student.route("/base")
def base():
    return render_template("student/base.html")

app/student/templates/student/attendance.html
{% extends "student/base.html" %}

{% block title %}Attendance - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Attendance page.</p>
{% endblock %}

app/student/templates/student/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Attendance Management System{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
</head>
<body>

    <!-- HEADER / NAVBAR -->
    <header>
        <nav>
            <ul>
                <li><a href="{{url_for('student.attendance')}}">Attendance</a></li>
                <li><a href="{{url_for('student.change_ip')}}">Chnage IP</a></li>
                <li><a href="{{url_for('auth.change_password')}}">Change Password</a></li>
                <li><a href="{{url_for('student.dashboard')}}">Dashboard</a></li>
                <li><a href="{{url_for('student.leave')}}">Leave</a></li>
                <li><a href="{{ url_for('student.profile')}}">Profile</a></li>
                <li><a href="{{ url_for('student.scan_qr')}}">Scanner</a></li>
                <li><a href="{{ url_for('student.timetable')}}">Timetable</a></li>
                <li><a href="{{ url_for('auth.logout')}}">Logout</a></li>
            </ul>
        </nav>
    </header>

    <!-- PAGE CONTENT -->
    <main>
        {% block content %}{% endblock %}
    </main>

    <!-- FOOTER -->
    <footer>
        <p>&copy; {{ 2025 }} Attendance Management System</p>
    </footer>

</body>
</html>

app/student/templates/student/change_ip.html
{% extends "student/base.html" %}

{% block title %}Change IP - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Change IP page.</p>
{% endblock %}

app/student/templates/student/dashboard.html
{% extends "student/base.html" %}

{% block title %}Dashboard - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Dashboard page.</p>
{% endblock %}

app/student/templates/student/leave.html
{% extends "student/base.html" %}

{% block title %}Leave - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Leave page.</p>
{% endblock %}

app/student/templates/student/profile.html
{% extends "student/base.html" %}

{% block title %}Profile - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Profile page.</p>
{% endblock %}

app/student/templates/student/scan_qr.html
{% extends "student/base.html" %}

{% block title %}Scanner - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Scan QR page.</p>
{% endblock %}

app/student/templates/student/timetable.html
{% extends "student/base.html" %}

{% block title %}Timetable - AMS{% endblock %}


{% block content %}
    <h1>Welcome to Attendance Management System</h1>
    <p>This is the Timetable page.</p>
{% endblock %}